### PR TITLE
targetSelectedIndex

### PR DESCRIPTION
**Pull request by schnittchen**
I found this useful so maybe someone else does.

### CODE REVIEW

**Comment by twopoint718** [comment]
@schnittchen this looks really good. Do you know how to do the "document, bump version, tag" dance? If you don't, here: https://github.com/elm-lang/elm-package#publishing-packages

**Comment by schnittchen** [comment]
First-timer here. I've added commits.

**Comment by schnittchen** [comment]
I'll soon be on holiday for a few days, if you like me to get this in please let me know what's missing.

**Comment by schnittchen** [comment]
So cool! :dancer:

**Pull request merged**
